const villageArray = [
    {
        "pincode": "274407",
        "villageNames": [
            "AHIRAULI TALWANT SHAHI",
            "BALUA SAMSERAHI",
            "BARAM TOLA",
            "BARWA",
            "CHAKHNI KHAS",
            "CHHAPARA AHIRAULI",
            "GANGUAWA",
            "PANDEY PATTI",
            "PARSAUNI URF DULMACHHAPRA SUMA ",
            "TEJWALIA",
            "BHATAWALIA",
            "BHELAHI",
            "HARIHARPUR",
            "HARPUR",
            "KHUDRA AHIRAULI",
            "KOINDI GOSAL PATTI",
            "KOINDI KHURD",
            "MANJHARIA",
            "SHAKARAPATTI",
            "ARAZI BHAGWANPUR",
            "BABHNAULI",
            "BARWA RAJAPAKAR BO",
            "DIBANI BANJARWA",
            "DUMAHI",
            "HATA ",
            "KONDHA",
            "KOINDI BARIYARPUR",
            "KOYAR PATTI",
            "PADARI BISHUN DAYAL",
            "BANWARIA RAMLAGAN  RAI",
            "BANWARIYA",
            "BHAGWANPUR",
            "BISHUNPURA",
            "DHURIYA IMLIYA BO",
            "LAXMIPUR  BABOO",
            "PADARI TILAK RAI",
            "PAGARA PRASAD GIRI",
            "PARSAUNI BUJURG",
            "RAJ MATHAULI",
            "TAMKUHI KASBA",
            "AHIRAULI",
            "BAGAHI",
            "BAGHAHI",
            "BARWA MISHRAULI",
            "BASDILA KHURD",
            "BAKHUA",
            "DUMMARBHAR",
            "LAWANIA",
            "TAMKUHI RAJ",
            "DHURIA KOT",
            "GHAZIPUR",
            "LAXMIPUR BUJURG",
            "PARSAUNI DOYAM",
            "PARSAUNI",
            "PIPARA BAGHEL",
            "TOLA SHIWATAMRAI",
            "AHIRAULI HANUMAN SINGH",
            "AJAY NAGAR",
            "BASANTPUR RAJA",
            "GADAI PATTI",
            "KOINDI BUJURG",
            "KOYARPATTI",
            "MAJHAUA",
            "MAKHUA",
            "MATHAULI",
            "PARSAUNI AUWAL",
            "RAJA  PAKAR",
            "TAMKUHI RAJ",
            "AHIRAULI RAJA",
            "BARWA RAJAPAKAR",
            "BASANTPUR HARICHARAN RAI",
            "BHARAPATIA",
            "DUBHA",
            "DUMAR BHAR",
            "HANUMAN GANJ",
            "HAUDA",
            "KAPAR DHIKA",
            "KHUDHI BHAGAT KA TOLA",
            "PADARI RAJA",
            "PAGARA GIRI",
            "PAGARA PARARI",
            "PANDEYPUR",
            "PANDEYPUR URF BASANTPUR",
            "PARSAURF SIRSIA MU",
            "PURAINA KATEYA",
            "SANGRAMPUR"
        ]
    },
    {

        "pincode": "274408",
        "villageNames": ["AHIRAULI  RAJA",
            "BABU PATTI",
            "BALPUR SHRINAGAR",
            "BANJARIYA BO",
            "HARAIA",
            "MAHUAWA",
            "MATHIA MAHABAL",
            "MUSHARI",
            "SHAMPUR",
            "BABHAIBAULI",
            "BARWA SERMA",
            "BASDILA",
            "JAMUNI",
            "KISUN MAHUAWAA",
            "MOGALPURA",
            "MOHAN MUNDERA",
            "MUNDERA",
            "TARKULAVA",
            "DEURWA",
            "KONHAWALIA BABURAI",
            "MADHOPUR",
            "MATHIA RATI",
            "PAHARPUR",
            "POKHAR BHINDA",
            "RATANPURA",
            "SINGAHA",
            "SISIA",
            "SONHULA RAMNAGAR",
            "AMWA",
            "HARAIYA",
            "HARIAPAR",
            "JALUWA",
            "KANCHANPUR BO",
            "KHEDANI",
            "MAHUWAHA BUJURG",
            "MARKANDEY",
            "OJHAULI",
            "PARASUNA",
            "PIPRA JHAM",
            "RAMPUR DHAUTAL",
            "SIRSIA PATTI  HUSEN  URF BASANTP",
            "HARPUR NIJAM",
            "KANAKPURA",
            "KONHAWALIA BHARTHRAI",
            "PAUHARI CHHAPAR ",
            "PIPRA  JHAM",
            "SHAHJAHA PUR",
            "SIRSIA GOTHA",
            "SIRSIAKHOIHA",
            "SUBANS CHHAPAR",
            "ASSITOLA URF MAINPUR",
            "BASANT PUR",
            "BAZARATAR MAHUAWA BO",
            "DEWRAWA",
            "FARENDHA",
            "KHAGI TOLA",
            "MAHUAPATAN ",
            "MAHUPATAN BO",
            "PIPRAHI",
            "PIPRAHIA",
            "SAMPUR  HATWA",
            "SEMARI",
            "SHAHJAN PUR",
            "SOHANARIYA",
            "TARKULWA",
            "BANZARIA",
            "JIGANIRAJA",
            "KANCHANPUR",
            "MAHEN BABU",
            "MAHUAWAN BAJARATAR",
            "MUSHAHARI",
            "PARSAUNI",
            "PIPRA KANAK",
            "SOHANRIA",
            "TURK PATTI",
            "BISHUNPURA URF CHIRKIHWA",
            "DWARIKA",
            "NARAINPUR",
            "PAGRA",
            "RAMPURGARH",
            "SAKHINI",
            "SEMARHAWA",
            "SIRSIA GOTHA",
            "SIRSIA KHOIYA ",
            "SISWA",]
    },
    {
        "pincode": "274409",
        "villageNames": [
            " SALEMGARH ",
            "BAHADUR PUR BO",
            " BAHIRA BARI",
            " FAGU CHHAPAR",
            " HAFUA BALRAM ",
            " JALAL CHHAPRA AHATMALI",
            "JAMSARA ",
            " JANGAL GHORATH ",
            "MATHIA ",
            " MUKUND CHHAPAR",
            " NARHWA ACHRAJ DUBEY ",
            " NONIYA PATTI ",
            " PIPRA MISRA",
            " PIRATHIPUR ",
            " SHAHDAULI ",
            " SISWAA AWWAL",
            " TARYA SUJAN ",
            " AHIRAULI DAAN ",
            " BHULI AGARWA ",
            " BICHPATWA ",
            " DANIARI ",
            " DUMARIA ",
            " HAFUA JEEVAN ",
            "JABAHI DAYAL BO ",
            " JAUH MALHI AHTAMALI ",
            " KHUDURA ",
            " MADHAVPUR KHURD ",
            " RAMPUR BANGRA ",
            "TINFARIA ",
            " BENI BHAR ",
            " GARHIA MOHAN ",
            " JAGDISHPUR ",
            " KATHWALIA URF HABIBPUR ",
            " MARAWA",
            " SALEMGARH ",
            "SISWA BUJURG ",
            " SRIRAM ",
            " TARYA ",
            "TARYA JAMIN ",
            "TARYA LACHHIRAM ",
            " ARAJI GADAI PATTI ",
            "BAGHACHAUR ",
            " BANS GAON",
            " BASDILA ",
            " CHHAPRA DALRAJ ",
            "DOMANTARYA",
            " HARIBANSH PATTI",
            " KHAIRATIA",
            " LATWA JIT",
            " MUKUNDPUR",
            " PARSAUN",
            " PATHARWA ",
            " SUMAHI MOHAN SINGH ",
            " SUMAHI RANI ",
            " TANDWA ",
            " TARAYA ",
            "BIRWAT KOMWALIA ",
            " GARHIACHINTA MANI ",
            " GOPALPUR ",
            " JAMSARIA ",
            " JHARWA ",
            " MAHESHPUR",
            "MATHAULI ",
            " PANDEYPUR ",
            " TARYA BAIKUNTH ",
            "TARYA SUNDER ",
            "AGARAWA ",
            " BAHADURPUR",
            " CHAUPTHIA ",
            " DHOKARAHA ",
            " HARHIA PATHAK ",
            " JALAL CHHAPRA ",
            " JAWHI DAYAL ",
            " SARAI KHURD ",
            "MATHIA SHRI RAM ",
            "BASDILA GUNAGAR ",
            "BEDUPAR MU ",
            "JABHI NARENDRA",
            "JAWHIDER HAKEEKAT PARSAUNI ",
            " MALHO ",
            "MATHIA SHRI RAM ",
            " MURAR BARI ",
            " NARAINPUR RAJA ",
            "NARHAWA DIH ",
            " TARYAHARKESH ",
            " TULSI PATTI ",
            " VEDUPAR ",
            " BAGHACHAUR BO ",
            " BAIJU PATTI ",
            ". BANKA KHAS ",
            "BEDUPAR AHATMALI ",
            " DOMATH ",
            " GOPALPUR ",
            " HAFUA CHATURBHUJ ",
            " KOHRA ",
            " LATWA MURLIDHAR ",
            " MEHADIYA BUJURG ",
            "MISHRAULI ",
            "NAINU PAHRU ",
            "SISWA DIGAR ",
            " SUMAHI BUJURG URF MEHEDIYA",
        ]

    }

]
module.exports = villageArray